spring:
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/tas_5
    driver-class-name: org.postgresql.Driver
    data: classpath*:schema.sql
    initialization-mode: always
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: pool
      maxLifetime: 2000000
      connectionTimeout: 30000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        default_schema: university
        show_sql: true
        format_sql: true

course:
  max-num-credits: 21
